version: '2'

services:
  redis:
    image: redis:latest

  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    links:
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "8080:8080"
    links:
      - api
    command: node node_modules/webpack-dev-server/bin/webpack-dev-server.js --hot --inline --content-base src/
